[package]
name = "colony-client"
version = "0.1.0"
edition = "2021"

[features]
dev = [
    "colony-core/dynamic",
]

[dependencies]
colony-core = { path = "../../libs/colony-core" }

[build-dependencies]
embed-resource = "1.4"
